FROM golang:1.14-alpine AS builder

WORKDIR /src

COPY . .

RUN go build -o dockerproxy

FROM alpine

COPY --from=builder /src/dockerproxy dockerproxy

CMD ["-certPath", "/certs/server-cert.pem", "-keyPath", "/certs/server-key.pem", "-caPath", "/certs/ca.pem", "-listenAddr", ":2376"]
ENTRYPOINT ["/dockerproxy"]
