FROM golang:1.14-alpine AS builder

WORKDIR /src

COPY . .

RUN go build -o dockerproxy

FROM alpine

USER root

RUN apk add --no-cache openssl

COPY --from=builder /src/dockerproxy dockerproxy

COPY openssl.cnf /etc/ssl/openssl.cnf

EXPOSE 2376

CMD []
ENTRYPOINT ["/dockerproxy"]
