ARG BUILD_IMAGE=golang:1.17-alpine
ARG RUN_IMAGE=alpine

FROM $BUILD_IMAGE AS builder

WORKDIR /src

COPY . .

RUN go build -o dockerproxy

FROM $RUN_IMAGE

USER root

RUN apk add --no-cache openssl

COPY --from=builder /src/dockerproxy dockerproxy

COPY openssl.cnf /etc/ssl/openssl.cnf

EXPOSE 2376

CMD []
ENTRYPOINT ["/dockerproxy"]
